### ISSUE TITLE
[Marker.io] Text under “our solutions” is not shown properly

### ISSUE THREAD

**Issue by himanshu201209** [NotAnother-NZ/proav#11]
[![Screenshot_2024-08-30_03-03-48.png](https://mrkr.io/s/66d13694320ff8994734a257/2)](https://mrkr.io/s/66d13694320ff8994734a257/0)

Steps to reproduce:go to our solutions section on home page
2) notice the text below the heading

Actual result: not shown properly

Expected result: it should be displayed properly

---

**Reported by:** Vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/66d13694320ff8994734a25a?advanced=1&comments=1)

**Source URL:** [https://proav-stg.webflow.io/](https://proav-stg.webflow.io/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/66d13694320ff8994734a25a?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>mobile</td></tr><tr><td><strong>Browser</strong></td><td>Safari 17.6</td></tr><tr><td><strong>Screen Size</strong></td><td>375 x 812</td></tr><tr><td><strong>OS</strong></td><td>iOS 17.6.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>375 x 710</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;3x</td></tr></table>

**Comment by vinod-ku1989** [comment]
stil seeing same behaviour:
https://drive.google.com/file/d/1M-Af3DjQcd-Kl-klkUWRfhpWlSixoSl0/view?usp=sharing

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/66d13694320ff8994734a25a?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
