### ISSUE TITLE
[Marker.io] phone field does not have the country flag field

### ISSUE THREAD

**Issue by himanshu201209** [NotAnother-NZ/proav#29]
[![Screenshot_2024-09-06_08-05-15.png](https://mrkr.io/s/66dab7bb8f7acd419410b104/2)](https://mrkr.io/s/66dab7bb8f7acd419410b104/0)

Steps to reproduce:
1) go to phone field
2) compare with figma

Actual result: flag field is not present which is there in figma

Expected result: if current behaviour is correct, then please ignore this one or elese please update this

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/66dab7bb8f7acd419410b108?advanced=1&comments=1)

**Source URL:** [https://proav-stg.webflow.io/contact](https://proav-stg.webflow.io/contact)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/66dab7bb8f7acd419410b108?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 128.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 (10.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 641</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by vinod-ku1989** [comment]
also please check if this is needed on home page too because we have similar contact form there too..

**Comment by himanshu201209** [comment]
Not required

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/66dab7bb8f7acd419410b108?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
