### ISSUE TITLE
[Marker.io] background is white on news details

### ISSUE THREAD

**Issue by himanshu201209** [NotAnother-NZ/proav#45]
[![Screenshot_2024-09-11_18-05-15.png](https://mrkr.io/s/66e1dbdb307811dfccabd8de/2)](https://mrkr.io/s/66e1dbdb307811dfccabd8de/0)

Steps to reproduce:
1) go to any news details page
2) notice background and compare with designs

Actual result:designs show greyish kind of background

Expected result: please check this once.if current one is correct/updated one, this can be ignored and closed else please change it.

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/66e1dbdb307811dfccabd8e1?advanced=1&comments=1)

**Source URL:** [https://proav-stg.webflow.io/news/pro-av-solutions-opens-its-newly-refurbished-workplace-in-queensland-2](https://proav-stg.webflow.io/news/pro-av-solutions-opens-its-newly-refurbished-workplace-in-queensland-2)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/66e1dbdb307811dfccabd8e1?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 128.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 (10.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1242 x 583</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.100000023841858x</td></tr></table>

**Comment by himanshu201209** [comment]
@vinod-ku1989 we have same white color in figma as well
https://www.figma.com/design/24Kx3Zs522OtUhnVB0PQQs/ProAV?node-id=869-14418&node-type=frame&t=8nN6XvbozGFQ6lJc-0

**Comment by vinod-ku1989** [comment]
mm..yeah right. probably some issue when we export the figma page. it was showing different color..
anyways. i am closing this.
![image](https://github.com/user-attachments/assets/41f932b8-c3ad-44f4-ba80-656b8d261441)

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/66e1dbdb307811dfccabd8e1?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
