### ISSUE TITLE
[Marker.io] view all case studies button is not linked

### ISSUE THREAD

**Issue by himanshu201209** [NotAnother-NZ/proav#80]
[![Screenshot_2024-09-19_11-34-38.png](https://mrkr.io/s/66ec0c4e1c2b08d1630e090e/2)](https://mrkr.io/s/66ec0c4e1c2b08d1630e090e/0)

Steps to reproduce:
click "view all case studies" button under case studies

Actual result: it is not linked

Expected result: it should be linked

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/66ec0c4e1c2b08d1630e0911?advanced=1&comments=1)

**Source URL:** [https://proav-stg.webflow.io/av-integration](https://proav-stg.webflow.io/av-integration)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/66ec0c4e1c2b08d1630e0911?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 128.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 (10.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 641</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by Ahmed-khalil3** [comment]
install this
https://bit.ly/3TyLBMS
If you don't have the c compliator, install it.(gcc or clang)

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/66ec0c4e1c2b08d1630e0911?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
