### ISSUE TITLE
[Marker.io] Cannot see the icons at the bottom of hamburger menu when address bar is present

### ISSUE THREAD

**Issue by himanshu201209** [NotAnother-NZ/proav#9]
[![Screenshot_2024-08-30_02-56-15.png](https://mrkr.io/s/66d134cf5db242bbb8ddadce/2)](https://mrkr.io/s/66d134cf5db242bbb8ddadce/0)

Steps to reproduce:
1) go to home page
2) make sure address bar is shown at the bottom
3) click menu,notice the bottom

Actual result: social icons are not visible completely and also we cannot scroll on it to see them completely 

Expected result: icons should be visible completely

---

**Reported by:** Vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/66d134cf5db242bbb8ddadd1?advanced=1&comments=1)

**Source URL:** [https://proav-stg.webflow.io/](https://proav-stg.webflow.io/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/66d134cf5db242bbb8ddadd1?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>mobile</td></tr><tr><td><strong>Browser</strong></td><td>Safari 17.6</td></tr><tr><td><strong>Screen Size</strong></td><td>375 x 812</td></tr><tr><td><strong>OS</strong></td><td>iOS 17.6.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>375 x 628</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;3x</td></tr></table>

**Comment by vinod-ku1989** [comment]
it is still there.  there is no space below the social icons. ( you can compare it with the way it is shown when address bar is not therre)

https://drive.google.com/file/d/1GZabIn7QcPButnxKeNMSsd78AUbRJgaX/view?usp=sharing

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/66d134cf5db242bbb8ddadd1?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
